### ISSUE TITLE
Rename this project to spurin/niksen

### ISSUE THREAD

**Issue by ams0** [spurin/idle#1]
I believe the philosophy behind this project is better represented by the Dutch word of `niksen` ([source](https://time.com/5622094/what-is-niksen/)). Hence, I propose to rename the project to `spurin/niksen`. I reckon that opening this very issue on a Friday goes against the very concept of niksen, but `helaas` (another great Dutch word).

**Comment by spurin** [comment]
Thanks @ams0 for the suggestion and for introducing me to the concept niksen! It’s fantastic and yes, I can see how it aligns with the project’s philosophy of, well, doing almost nothing.

I think the current name idle, strikes a nice balance of simplicity and recognition. It’s also already living its best life in Docker Hub under this name 😆

Love the spirit of niksen and I’ll be channeling it over the xmas period!

Appreciate you as always and thanks for the idea, hope that idle proves itself worthy of its minimalistic aspirations and the close connections to niksen!
