### ISSUE TITLE
logo inconsistent

### ISSUE THREAD

**Issue by SylvanFranklin** [spurin/idle#2]
**Awesome** project with a great sense of humor! However I am personally against AI Generated logos for projects on Github. 

1. They take up vertical space making people scroll, annoying on mobile
2. They make the page load slower
3. They feel kinda soulless
4. In this sick ass project, having a crazy big logo would kinda go against the philosophy of nothingness

I would remove it or just acquire a much more simple one, I could take a crack at it too if you would like. Again great project, just thought I'd give my two cents, feel free to ignore as it is your thing! Thanks!

**Comment by spurin** [comment]
Hey, Hiya @SylvanFranklin,

Thanks so much for your feedback on this. I made it as a quick bit of fun so the logo, was also done quite quickly. I hear you though.

If you've got the cycles and would like to have a crack at making a logo then it would be more than welcome! Only if you've got time though, again, this was meant as a fun project, even though it serves a great purpose also!

Kind Regards


James

**Comment by spurin** [comment]
@SylvanFranklin, I have a freepik subscription which allows the creation of SVG's as icon's under their AI offering, these are less in your face than the standard AI images like the one I'm using now. Also, with them being SVG's they are ultra small. What do you think of some of these as options? (as they are svgs, I can edit and remove aspects of them also). 

<img src="https://github.com/user-attachments/assets/f57dde42-a283-4e64-8b3b-9c0cdda964f1" width="100" alt="1" /> <img src="https://github.com/user-attachments/assets/64a0dcf8-bc27-4b68-ab93-a4aa4d9c117a" width="100" alt="2" /> <img src="https://github.com/user-attachments/assets/370e946f-f411-4f57-a6f0-28c163724a5a" width="100" alt="3" /> <img src="https://github.com/user-attachments/assets/4f7c2d5e-1dd9-4f26-8783-ec8dca760271" width="100" alt="4" />

I personally like #3. The aspect ratio is what I'd hope for on the container positioning.

**Comment by SylvanFranklin** [comment]
Great idea those are all a huge improvement. I agree with you about 3 in both points. I think that the rotation of 1 and 4 are nicely forward facing, which could be what you mean by Z positioning. Ideally the aspect ratio of 2 rotation of 4, and possibly white text on a non-blue background of 2 Don't go crazy on a project that is just fun, but that's my two cents haha!

**Comment by spurin** [comment]
Thanks! It's quite hit and miss trying to get the AI to do this well and as they are not 3D objects, I'll go with #3 and see if I can get the white outline, I liked that a lot. Appreciate your candid feedback on it!

**Comment by spurin** [comment]
After some tweaks @SylvanFranklin 

<img src="https://github.com/user-attachments/assets/10b95ffd-b9ef-4e7e-9c6a-052ecc00f43c" width="200" alt="1" />

**Comment by SylvanFranklin** [comment]
Perfect that looks awesome!

**Comment by spurin** [comment]
This is complete @SylvanFranklin, again, appreciate your candid feedback and discussion. I've added a thanks section also with your GitHub id 🚀

**Comment by SylvanFranklin** [comment]
Thank you! I'm just starting my open source career and that's super helpful for traction on my projects! Glad to help!

**Comment by spurin** [comment]
My pleasure @SylvanFranklin - This is what this community is all about, best of luck with your projects and look forward to future collaborations!
